//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosyCrow.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RosyCrow.Resources.Localization.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string BookmarksPage_Title {
            get {
                return ResourceManager.GetString("BookmarksPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this bookmark?.
        /// </summary>
        internal static string BookmarksPage_TryDeleteBookmark_Confirm {
            get {
                return ResourceManager.GetString("BookmarksPage_TryDeleteBookmark_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Bookmark.
        /// </summary>
        internal static string BookmarksPage_TryDeleteBookmark_Delete_Bookmark {
            get {
                return ResourceManager.GetString("BookmarksPage_TryDeleteBookmark_Delete_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy address.
        /// </summary>
        internal static string BrowserView_CreateWebViewContextMenu_Copy_address {
            get {
                return ResourceManager.GetString("BrowserView_CreateWebViewContextMenu_Copy_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy text.
        /// </summary>
        internal static string BrowserView_CreateWebViewContextMenu_Copy_text {
            get {
                return ResourceManager.GetString("BrowserView_CreateWebViewContextMenu_Copy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Page {0} of {1}.
        /// </summary>
        internal static string HistoryPage_LoadCurrentPage__Page__0__of__1_ {
            get {
                return ResourceManager.GetString("HistoryPage_LoadCurrentPage__Page__0__of__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page history.
        /// </summary>
        internal static string HistoryPage_Save_page_history {
            get {
                return ResourceManager.GetString("HistoryPage_Save_page_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryPage_Title {
            get {
                return ResourceManager.GetString("HistoryPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} visited pages deleted.
        /// </summary>
        internal static string HistoryPage_TryClearHistory__0__visited_pages_deleted {
            get {
                return ResourceManager.GetString("HistoryPage_TryClearHistory__0__visited_pages_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        internal static string HistoryPage_TryClearHistory_Clear_History {
            get {
                return ResourceManager.GetString("HistoryPage_TryClearHistory_Clear_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear your stored history?.
        /// </summary>
        internal static string HistoryPage_TryClearHistory_Confirm {
            get {
                return ResourceManager.GetString("HistoryPage_TryClearHistory_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this identity?.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Confirm {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Identity.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Delete_Identity {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Delete_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete identity.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Failed_to_delete_identity {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Failed_to_delete_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity deleted.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Identity_deleted {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Identity_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate to protect the new identity&apos;s encryption key..
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Authenticate {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not protect the identity.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Could_not_protect_the_identity {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Could_not_protect_the_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Identity.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Generate_Identity {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Generate_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name you would like to use for this key..
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Prompt {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure this identity with your device credentials?.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Secure {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure the Identity.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Secure_the_Identity {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Secure_the_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string IdentityPage_Title {
            get {
                return ResourceManager.GetString("IdentityPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string MainPage_Menu_Bookmarks {
            get {
                return ResourceManager.GetString("MainPage_Menu_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string MainPage_Menu_History {
            get {
                return ResourceManager.GetString("MainPage_Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string MainPage_Menu_Identity {
            get {
                return ResourceManager.GetString("MainPage_Menu_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string MainPage_Menu_Print {
            get {
                return ResourceManager.GetString("MainPage_Menu_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainPage_Menu_Settings {
            get {
                return ResourceManager.GetString("MainPage_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No home URL has been set. Long-press the Home button to set one..
        /// </summary>
        internal static string MainPage_TryLoadHomeUrl_No_home_set {
            get {
                return ResourceManager.GetString("MainPage_TryLoadHomeUrl_No_home_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home set.
        /// </summary>
        internal static string MainPage_TrySetHomeUrl_Home_set {
            get {
                return ResourceManager.GetString("MainPage_TrySetHomeUrl_Home_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark added.
        /// </summary>
        internal static string MainPage_TryToggleBookmarked_Bookmark_added {
            get {
                return ResourceManager.GetString("MainPage_TryToggleBookmarked_Bookmark_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark removed.
        /// </summary>
        internal static string MainPage_TryToggleBookmarked_Bookmark_removed {
            get {
                return ResourceManager.GetString("MainPage_TryToggleBookmarked_Bookmark_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Rosy Crow.
        /// </summary>
        internal static string SettingsPage_About {
            get {
                return ResourceManager.GetString("SettingsPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History page size.
        /// </summary>
        internal static string SettingsPage_History_page_size {
            get {
                return ResourceManager.GetString("SettingsPage_History_page_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show images inline (very slow at the moment).
        /// </summary>
        internal static string SettingsPage_InlineImages {
            get {
                return ResourceManager.GetString("SettingsPage_InlineImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingsPage_Theme {
            get {
                return ResourceManager.GetString("SettingsPage_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
    }
}
