//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosyCrow.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RosyCrow.Resources.Localization.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to import {0} tabs?.
        /// </summary>
        internal static string App_HandleImportTabsIntent_Do_you_want_to_import__0__tabs_ {
            get {
                return ResourceManager.GetString("App_HandleImportTabsIntent_Do_you_want_to_import__0__tabs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tabs.
        /// </summary>
        internal static string App_HandleImportTabsIntent_Import_Tabs {
            get {
                return ResourceManager.GetString("App_HandleImportTabsIntent_Import_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string App_HandleImportTabsIntent_No {
            get {
                return ResourceManager.GetString("App_HandleImportTabsIntent_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tabs were imported because something went wrong.
        /// </summary>
        internal static string App_HandleImportTabsIntent_No_tabs_were_imported_because_something_went_wrong {
            get {
                return ResourceManager.GetString("App_HandleImportTabsIntent_No_tabs_were_imported_because_something_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains no tabs.
        /// </summary>
        internal static string App_HandleImportTabsIntent_The_file_contains_no_tabs {
            get {
                return ResourceManager.GetString("App_HandleImportTabsIntent_The_file_contains_no_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is formatted incorrectly.
        /// </summary>
        internal static string App_HandleImportTabsIntent_The_file_is_formatted_incorrectly {
            get {
                return ResourceManager.GetString("App_HandleImportTabsIntent_The_file_is_formatted_incorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string App_HandleImportTabsIntent_Yes {
            get {
                return ResourceManager.GetString("App_HandleImportTabsIntent_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, so the link could not be opened.
        /// </summary>
        internal static string App_HandleNavigationIntent_Something_went_wrong__so_the_link_could_not_be_opened {
            get {
                return ResourceManager.GetString("App_HandleNavigationIntent_Something_went_wrong__so_the_link_could_not_be_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string BookmarksPage_Title {
            get {
                return ResourceManager.GetString("BookmarksPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this bookmark?.
        /// </summary>
        internal static string BookmarksPage_TryDeleteBookmark_Confirm {
            get {
                return ResourceManager.GetString("BookmarksPage_TryDeleteBookmark_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Bookmark.
        /// </summary>
        internal static string BookmarksPage_TryDeleteBookmark_Delete_Bookmark {
            get {
                return ResourceManager.GetString("BookmarksPage_TryDeleteBookmark_Delete_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tabs.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_All_Tabs {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_All_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Arrange {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Arrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Bookmark {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Close {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Close_All {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Close_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Copy_URL {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Copy_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Export {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch (favicon.txt).
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Fetch__favicon_txt_ {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Fetch__favicon_txt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Icon {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Import {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Bookmark.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Remove_Bookmark {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Remove_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Reset {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Custom.
        /// </summary>
        internal static string BrowserTab_BuildContextMenu_Set_Custom {
            get {
                return ResourceManager.GetString("BrowserTab_BuildContextMenu_Set_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL.
        /// </summary>
        internal static string BrowserView_BuildContextMenu_Copy_URL {
            get {
                return ResourceManager.GetString("BrowserView_BuildContextMenu_Copy_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in New Tab.
        /// </summary>
        internal static string BrowserView_BuildContextMenu_Open_in_New_Tab {
            get {
                return ResourceManager.GetString("BrowserView_BuildContextMenu_Open_in_New_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share URL.
        /// </summary>
        internal static string BrowserView_BuildContextMenu_Share_URL {
            get {
                return ResourceManager.GetString("BrowserView_BuildContextMenu_Share_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy address.
        /// </summary>
        internal static string BrowserView_CreateWebViewContextMenu_Copy_address {
            get {
                return ResourceManager.GetString("BrowserView_CreateWebViewContextMenu_Copy_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy text.
        /// </summary>
        internal static string BrowserView_CreateWebViewContextMenu_Copy_text {
            get {
                return ResourceManager.GetString("BrowserView_CreateWebViewContextMenu_Copy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} instances.
        /// </summary>
        internal static string BrowserView_FindNext_Found__0__instances {
            get {
                return ResourceManager.GetString("BrowserView_FindNext_Found__0__instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instances found.
        /// </summary>
        internal static string BrowserView_FindNext_No_instances_found {
            get {
                return ResourceManager.GetString("BrowserView_FindNext_No_instances_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string BrowserView_LoadPage_Error {
            get {
                return ResourceManager.GetString("BrowserView_LoadPage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Required.
        /// </summary>
        internal static string BrowserView_LoadPage_Input_Required {
            get {
                return ResourceManager.GetString("BrowserView_LoadPage_Input_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BrowserView_LoadPage_OK {
            get {
                return ResourceManager.GetString("BrowserView_LoadPage_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Open URL.
        /// </summary>
        internal static string BrowserView_PageWebView_OnNavigating_Cannot_Open_URL {
            get {
                return ResourceManager.GetString("BrowserView_PageWebView_OnNavigating_Cannot_Open_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No app is configured to open {0} links..
        /// </summary>
        internal static string BrowserView_PageWebView_OnNavigating_No_app_is_configured_to_open__0__links_ {
            get {
                return ResourceManager.GetString("BrowserView_PageWebView_OnNavigating_No_app_is_configured_to_open__0__links_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BrowserView_PageWebView_OnNavigating_OK {
            get {
                return ResourceManager.GetString("BrowserView_PageWebView_OnNavigating_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_Cancel {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Problem.
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_Certificate_Problem {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_Certificate_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host&apos;s certificate has changed..
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_has_changed_ {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_has_changed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host&apos;s certificate has expired..
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_has_expired_ {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_has_expired_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host&apos;s certificate is invalid..
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_is_invalid_ {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_is_invalid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host&apos;s certificate is missing required information..
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_is_missing_required_information_ {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_is_missing_re" +
                        "quired_information_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host&apos;s certificate is not valid yet..
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_is_not_valid_yet_ {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_The_host_s_certificate_is_not_valid_" +
                        "yet_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name on the server&apos;s certificate is incorrect..
        /// </summary>
        internal static string BrowserView_RemoteCertificateInvalidCallback_The_name_on_the_server_s_certificate_is_incorrect_ {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateInvalidCallback_The_name_on_the_server_s_certificate" +
                        "_is_incorrect_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the host&apos;s new certificate and continue?  Its fingerprint is {0}..
        /// </summary>
        internal static string BrowserView_RemoteCertificateUnrecognizedCallback_Accept_the_host_s_new_certificate_and_continue___Its_fingerprint_is__0__ {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateUnrecognizedCallback_Accept_the_host_s_new_certifica" +
                        "te_and_continue___Its_fingerprint_is__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Certificate.
        /// </summary>
        internal static string BrowserView_RemoteCertificateUnrecognizedCallback_New_Certificate {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateUnrecognizedCallback_New_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BrowserView_RemoteCertificateUnrecognizedCallback_No {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateUnrecognizedCallback_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BrowserView_RemoteCertificateUnrecognizedCallback_Yes {
            get {
                return ResourceManager.GetString("BrowserView_RemoteCertificateUnrecognizedCallback_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string CertificatePage_CertificatePage_Copied {
            get {
                return ResourceManager.GetString("CertificatePage_CertificatePage_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string CertificatePage_Expiration {
            get {
                return ResourceManager.GetString("CertificatePage_Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        internal static string CertificatePage_Fingerprint {
            get {
                return ResourceManager.GetString("CertificatePage_Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string CertificatePage_Subject {
            get {
                return ResourceManager.GetString("CertificatePage_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string ExportIdentityPage_Alias {
            get {
                return ResourceManager.GetString("ExportIdentityPage_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportIdentityPage_Export {
            get {
                return ResourceManager.GetString("ExportIdentityPage_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string ExportIdentityPage_ExportIdentityPage_Copied {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportIdentityPage_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identities cannot be exported unless Rosy Crow has permission to write to you device&apos;s storage.
        ///
        ///Try again after you&apos;ve granted the app permission to do so..
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_ {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate for Identity {ID} exported encrypted to {Path}.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Certificate_for_Identity__ID__exported_encrypted_to__Path_ {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Certificate_for_Identity__ID__exported_encrypted_to_" +
                        "_Path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate for Identity {ID} exported unencrypted to {Path}.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Certificate_for_Identity__ID__exported_unencrypted_to__Path_ {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Certificate_for_Identity__ID__exported_unencrypted_t" +
                        "o__Path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the file.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Could_not_save_the_file {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Could_not_save_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password or disable password protection.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Enter_a_password_or_disable_password_protection {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Enter_a_password_or_disable_password_protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting the certificate for Identity {ID} ({Name}).
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Exporting_the_certificate_for_Identity__ID____Name__ {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Exporting_the_certificate_for_Identity__ID____Name__" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the certificate.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Failed_to_export_the_certificate {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Failed_to_export_the_certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacking Permission.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Lacking_Permission {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Lacking_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_OK {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password copied to the clipboard.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_Password_copied_to_the_clipboard {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_Password_copied_to_the_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity could not be decrypted.
        /// </summary>
        internal static string ExportIdentityPage_ExportKey_The_identity_could_not_be_decrypted {
            get {
                return ResourceManager.GetString("ExportIdentityPage_ExportKey_The_identity_could_not_be_decrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        internal static string ExportIdentityPage_Fingerprint {
            get {
                return ResourceManager.GetString("ExportIdentityPage_Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string ExportIdentityPage_Password {
            get {
                return ResourceManager.GetString("ExportIdentityPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Identity.
        /// </summary>
        internal static string ExportIdentityPage_Title {
            get {
                return ResourceManager.GetString("ExportIdentityPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Global_OK {
            get {
                return ResourceManager.GetString("Global_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Global_Yes {
            get {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Page {0} of {1}.
        /// </summary>
        internal static string HistoryPage_LoadCurrentPage__Page__0__of__1_ {
            get {
                return ResourceManager.GetString("HistoryPage_LoadCurrentPage__Page__0__of__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page history.
        /// </summary>
        internal static string HistoryPage_Save_page_history {
            get {
                return ResourceManager.GetString("HistoryPage_Save_page_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryPage_Title {
            get {
                return ResourceManager.GetString("HistoryPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} visited pages deleted.
        /// </summary>
        internal static string HistoryPage_TryClearHistory__0__visited_pages_deleted {
            get {
                return ResourceManager.GetString("HistoryPage_TryClearHistory__0__visited_pages_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        internal static string HistoryPage_TryClearHistory_Clear_History {
            get {
                return ResourceManager.GetString("HistoryPage_TryClearHistory_Clear_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear your stored history?.
        /// </summary>
        internal static string HistoryPage_TryClearHistory_Confirm {
            get {
                return ResourceManager.GetString("HistoryPage_TryClearHistory_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this identity?.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Confirm {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Identity.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Delete_Identity {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Delete_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete identity.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Failed_to_delete_identity {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Failed_to_delete_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity deleted.
        /// </summary>
        internal static string IdentityPage_DeleteKey_Identity_deleted {
            get {
                return ResourceManager.GetString("IdentityPage_DeleteKey_Identity_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate to protect the new identity&apos;s encryption key..
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Authenticate {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not protect the identity.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Could_not_protect_the_identity {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Could_not_protect_the_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Identity.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Generate_Identity {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Generate_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name you would like to use for this key..
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Prompt {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure this identity with your device credentials?.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Secure {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure the Identity.
        /// </summary>
        internal static string IdentityPage_GenerateNewKey_Secure_the_Identity {
            get {
                return ResourceManager.GetString("IdentityPage_GenerateNewKey_Secure_the_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string IdentityPage_Title {
            get {
                return ResourceManager.GetString("IdentityPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export this identity.
        /// </summary>
        internal static string IdentityPage_TryOpeningExportKeyPage_Cannot_export_this_identity {
            get {
                return ResourceManager.GetString("IdentityPage_TryOpeningExportKeyPage_Cannot_export_this_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not unlock the identity.
        /// </summary>
        internal static string IdentityService_DerivePassword_Could_not_unlock_the_identity {
            get {
                return ResourceManager.GetString("IdentityService_DerivePassword_Could_not_unlock_the_identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock the Identity.
        /// </summary>
        internal static string IdentityService_DerivePassword_Unlock_the_Identity {
            get {
                return ResourceManager.GetString("IdentityService_DerivePassword_Unlock_the_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock the identity using your device&apos;s credential..
        /// </summary>
        internal static string IdentityService_DerivePassword_Unlock_the_identity_using_your_device_s_credential_ {
            get {
                return ResourceManager.GetString("IdentityService_DerivePassword_Unlock_the_identity_using_your_device_s_credential" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        internal static string ImportIdentityPage_Fingerprint {
            get {
                return ResourceManager.GetString("ImportIdentityPage_Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportIdentityPage_Import {
            get {
                return ResourceManager.GetString("ImportIdentityPage_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string ImportIdentityPage_ImportIdentityPage_Copied {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportIdentityPage_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the certificate file.
        /// </summary>
        internal static string ImportIdentityPage_ImportIdentityPage_OnAppearing_Failed_to_read_the_certificate_file {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportIdentityPage_OnAppearing_Failed_to_read_the_certificate_" +
                        "file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption Failed.
        /// </summary>
        internal static string ImportIdentityPage_ImportKey_Decryption_Failed {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportKey_Decryption_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Private Key.
        /// </summary>
        internal static string ImportIdentityPage_ImportKey_Missing_Private_Key {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportKey_Missing_Private_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ImportIdentityPage_ImportKey_OK {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportKey_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate&apos;s private key could not be decrypted.  The password is likely incorrect..
        /// </summary>
        internal static string ImportIdentityPage_ImportKey_The_certificate_s_private_key_could_not_be_decrypted___The_password_is_likely_incorrect_ {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportKey_The_certificate_s_private_key_could_not_be_decrypted" +
                        "___The_password_is_likely_incorrect_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import could not be completed.
        /// </summary>
        internal static string ImportIdentityPage_ImportKey_The_import_could_not_be_completed {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportKey_The_import_could_not_be_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected certificate file lacks a private key, and therefore cannot be imported..
        /// </summary>
        internal static string ImportIdentityPage_ImportKey_The_selected_certificate_file_lacks_a_private_key__and_therefore_cannot_be_imported_ {
            get {
                return ResourceManager.GetString("ImportIdentityPage_ImportKey_The_selected_certificate_file_lacks_a_private_key__a" +
                        "nd_therefore_cannot_be_imported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ImportIdentityPage_Password {
            get {
                return ResourceManager.GetString("ImportIdentityPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protected.
        /// </summary>
        internal static string ImportIdentityPage_PasswordProtected {
            get {
                return ResourceManager.GetString("ImportIdentityPage_PasswordProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to secure the imported identity with your device credentials?.
        /// </summary>
        internal static string ImportIdentityPage_PresentProtectionPrompt_Do_you_want_to_secure_the_imported_identity_with_your_device_credentials_ {
            get {
                return ResourceManager.GetString("ImportIdentityPage_PresentProtectionPrompt_Do_you_want_to_secure_the_imported_ide" +
                        "ntity_with_your_device_credentials_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Identity.
        /// </summary>
        internal static string ImportIdentityPage_PresentProtectionPrompt_Import_Identity {
            get {
                return ResourceManager.GetString("ImportIdentityPage_PresentProtectionPrompt_Import_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ImportIdentityPage_Subject {
            get {
                return ResourceManager.GetString("ImportIdentityPage_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string MainPage_Bookmark {
            get {
                return ResourceManager.GetString("MainPage_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle a bookmark for the current page.
        /// </summary>
        internal static string MainPage_BookmarkHint {
            get {
                return ResourceManager.GetString("MainPage_BookmarkHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in page.
        /// </summary>
        internal static string MainPage_FindInPage {
            get {
                return ResourceManager.GetString("MainPage_FindInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MainPage_Home {
            get {
                return ResourceManager.GetString("MainPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold to set a home page, tap to navigate to the home page.
        /// </summary>
        internal static string MainPage_HomeHint {
            get {
                return ResourceManager.GetString("MainPage_HomeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That address is invalid.
        /// </summary>
        internal static string MainPage_MainPage_That_address_is_invalid {
            get {
                return ResourceManager.GetString("MainPage_MainPage_That_address_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string MainPage_Menu_Bookmarks {
            get {
                return ResourceManager.GetString("MainPage_Menu_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string MainPage_Menu_History {
            get {
                return ResourceManager.GetString("MainPage_Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string MainPage_Menu_Identity {
            get {
                return ResourceManager.GetString("MainPage_Menu_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string MainPage_Menu_Print {
            get {
                return ResourceManager.GetString("MainPage_Menu_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainPage_Menu_Settings {
            get {
                return ResourceManager.GetString("MainPage_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string MainPage_Next {
            get {
                return ResourceManager.GetString("MainPage_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the next occurrence of the text being searched for.
        /// </summary>
        internal static string MainPage_NextHint {
            get {
                return ResourceManager.GetString("MainPage_NextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MainPage_PageInformation {
            get {
                return ResourceManager.GetString("MainPage_PageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display information about the page.
        /// </summary>
        internal static string MainPage_PageInformationHint {
            get {
                return ResourceManager.GetString("MainPage_PageInformationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Page.
        /// </summary>
        internal static string MainPage_TryFindInPage_Find_in_Page {
            get {
                return ResourceManager.GetString("MainPage_TryFindInPage_Find_in_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text to search for..
        /// </summary>
        internal static string MainPage_TryFindInPage_InitialPrompt {
            get {
                return ResourceManager.GetString("MainPage_TryFindInPage_InitialPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the text to search for, or clear-out this prompt to cancel the search..
        /// </summary>
        internal static string MainPage_TryFindInPage_OngoingPrompt {
            get {
                return ResourceManager.GetString("MainPage_TryFindInPage_OngoingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No home URL has been set. Long-press the Home button to set one..
        /// </summary>
        internal static string MainPage_TryLoadHomeUrl_No_home_set {
            get {
                return ResourceManager.GetString("MainPage_TryLoadHomeUrl_No_home_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home set.
        /// </summary>
        internal static string MainPage_TrySetHomeUrl_Home_set {
            get {
                return ResourceManager.GetString("MainPage_TrySetHomeUrl_Home_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home URL cleared.
        /// </summary>
        internal static string MainPage_TrySetHomeUrl_Home_URL_cleared {
            get {
                return ResourceManager.GetString("MainPage_TrySetHomeUrl_Home_URL_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark added.
        /// </summary>
        internal static string MainPage_TryToggleBookmarked_Bookmark_added {
            get {
                return ResourceManager.GetString("MainPage_TryToggleBookmarked_Bookmark_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark removed.
        /// </summary>
        internal static string MainPage_TryToggleBookmarked_Bookmark_removed {
            get {
                return ResourceManager.GetString("MainPage_TryToggleBookmarked_Bookmark_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm every host certificate.
        /// </summary>
        internal static string SettingPage_ConfirmEveryCertificate {
            get {
                return ResourceManager.GetString("SettingPage_ConfirmEveryCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Rosy Crow.
        /// </summary>
        internal static string SettingsPage_About {
            get {
                return ResourceManager.GetString("SettingsPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow IPv6 requests.
        /// </summary>
        internal static string SettingsPage_AllowIPv6Requests {
            get {
                return ResourceManager.GetString("SettingsPage_AllowIPv6Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotate non-Gemini links.
        /// </summary>
        internal static string SettingsPage_Annotate_links {
            get {
                return ResourceManager.GetString("SettingsPage_Annotate_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string SettingsPage_Body {
            get {
                return ResourceManager.GetString("SettingsPage_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string SettingsPage_CopyVersion {
            get {
                return ResourceManager.GetString("SettingsPage_CopyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the version number.
        /// </summary>
        internal static string SettingsPage_CopyVersionHint {
            get {
                return ResourceManager.GetString("SettingsPage_CopyVersionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs cannot be exported unless Rosy Crow has permission to write to you device&apos;s storage.
        ///
        ///Try again after you&apos;ve granted the app permission to do so..
        /// </summary>
        internal static string SettingsPage_ExportErrorLogArchive_ {
            get {
                return ResourceManager.GetString("SettingsPage_ExportErrorLogArchive_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save archive.
        /// </summary>
        internal static string SettingsPage_ExportErrorLogArchive_Could_not_save_archive {
            get {
                return ResourceManager.GetString("SettingsPage_ExportErrorLogArchive_Could_not_save_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacking Permission.
        /// </summary>
        internal static string SettingsPage_ExportErrorLogArchive_Lacking_Permission {
            get {
                return ResourceManager.GetString("SettingsPage_ExportErrorLogArchive_Lacking_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SettingsPage_ExportErrorLogArchive_OK {
            get {
                return ResourceManager.GetString("SettingsPage_ExportErrorLogArchive_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no error logs to export.
        /// </summary>
        internal static string SettingsPage_ExportErrorLogArchive_There_are_no_error_logs_to_export {
            get {
                return ResourceManager.GetString("SettingsPage_ExportErrorLogArchive_There_are_no_error_logs_to_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Error Logs.
        /// </summary>
        internal static string SettingsPage_ExportErrorLogs {
            get {
                return ResourceManager.GetString("SettingsPage_ExportErrorLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Sizes.
        /// </summary>
        internal static string SettingsPage_Font_Sizes {
            get {
                return ResourceManager.GetString("SettingsPage_Font_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 1.
        /// </summary>
        internal static string SettingsPage_Heading_1 {
            get {
                return ResourceManager.GetString("SettingsPage_Heading_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 2.
        /// </summary>
        internal static string SettingsPage_Heading_2 {
            get {
                return ResourceManager.GetString("SettingsPage_Heading_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 3.
        /// </summary>
        internal static string SettingsPage_Heading_3 {
            get {
                return ResourceManager.GetString("SettingsPage_Heading_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide menu pull tab.
        /// </summary>
        internal static string SettingsPage_HidePullTab {
            get {
                return ResourceManager.GetString("SettingsPage_HidePullTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History page size.
        /// </summary>
        internal static string SettingsPage_History_page_size {
            get {
                return ResourceManager.GetString("SettingsPage_History_page_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show images inline (pages will take longer to load).
        /// </summary>
        internal static string SettingsPage_InlineImages {
            get {
                return ResourceManager.GetString("SettingsPage_InlineImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string SettingsPage_Preview {
            get {
                return ResourceManager.GetString("SettingsPage_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An example of a page rendered using the selected theme.
        /// </summary>
        internal static string SettingsPage_PreviewHint {
            get {
                return ResourceManager.GetString("SettingsPage_PreviewHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string SettingsPage_SettingsPage_Copied {
            get {
                return ResourceManager.GetString("SettingsPage_SettingsPage_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}, build {1}.
        /// </summary>
        internal static string SettingsPage_SettingsPage_OnLoaded_Version__0___build__1_ {
            get {
                return ResourceManager.GetString("SettingsPage_SettingsPage_OnLoaded_Version__0___build__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs.
        /// </summary>
        internal static string SettingsPage_Show_tabs {
            get {
                return ResourceManager.GetString("SettingsPage_Show_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe to move between tabs.
        /// </summary>
        internal static string SettingsPage_Swipe_to_move_between_tabs {
            get {
                return ResourceManager.GetString("SettingsPage_Swipe_to_move_between_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab button side.
        /// </summary>
        internal static string SettingsPage_Tab_button_side {
            get {
                return ResourceManager.GetString("SettingsPage_Tab_button_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingsPage_Theme {
            get {
                return ResourceManager.GetString("SettingsPage_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a custom font size.
        /// </summary>
        internal static string SettingsPage_Use_a_custom_font_size {
            get {
                return ResourceManager.GetString("SettingsPage_Use_a_custom_font_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string SettingsPage_Version {
            get {
                return ResourceManager.GetString("SettingsPage_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s version number.
        /// </summary>
        internal static string SettingsPage_VersionHint {
            get {
                return ResourceManager.GetString("SettingsPage_VersionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        internal static string SettingsPage_WhatsNew {
            get {
                return ResourceManager.GetString("SettingsPage_WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs cannot be exported unless Rosy Crow has permission to write to you device&apos;s storage.
        ///
        ///Try again after you&apos;ve granted the app permission to do so..
        /// </summary>
        internal static string TabCollection_BrowserTab_OnExportRequested_ {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnExportRequested_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the file.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnExportRequested_Could_not_save_the_file {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnExportRequested_Could_not_save_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lacking Permission.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnExportRequested_Lacking_Permission {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnExportRequested_Lacking_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was exported because something went wrong.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnExportRequested_Nothing_was_exported_because_something_went_wrong {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnExportRequested_Nothing_was_exported_because_something" +
                        "_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnExportRequested_OK {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnExportRequested_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch the icon due to an error.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnFetchingIcon_Failed_to_fetch_the_icon_due_to_an_error {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnFetchingIcon_Failed_to_fetch_the_icon_due_to_an_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon updated.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnFetchingIcon_Icon_updated {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnFetchingIcon_Icon_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No icon available.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnFetchingIcon_No_icon_available {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnFetchingIcon_No_icon_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} tabs.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnImportRequested_Imported__0__tabs {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnImportRequested_Imported__0__tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported a tab.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnImportRequested_Imported_a_tab {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnImportRequested_Imported_a_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tabs were imported because something went wrong.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnImportRequested_No_tabs_were_imported_because_something_went_wrong {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnImportRequested_No_tabs_were_imported_because_somethin" +
                        "g_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a JSON File to Import.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnImportRequested_Select_a_JSON_File_to_Import {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnImportRequested_Select_a_JSON_File_to_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is formatted incorrectly.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnImportRequested_The_file_is_formatted_incorrectly {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnImportRequested_The_file_is_formatted_incorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tabs to import.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnImportRequested_There_are_no_tabs_to_import {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnImportRequested_There_are_no_tabs_to_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tabs will be closed.
        ///Proceed?.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnRemoveAllRequested_ {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnRemoveAllRequested_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnRemoveAllRequested_Close_All {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnRemoveAllRequested_Close_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnRemoveAllRequested_No {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnRemoveAllRequested_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnRemoveAllRequested_Yes {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnRemoveAllRequested_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back or select a tab when finished.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnReorderingRequested_Go_back_or_select_a_tab_when_finished {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnReorderingRequested_Go_back_or_select_a_tab_when_finis" +
                        "hed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon has been reset.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnResettingIcon_The_icon_has_been_reset {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnResettingIcon_The_icon_has_been_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter what you would like this tab&apos;s icon to be.
        ///One or two letters or numbers may be entered, or a single emoji character..
        /// </summary>
        internal static string TabCollection_BrowserTab_OnSettingCustomIcon_ {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnSettingCustomIcon_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Icon.
        /// </summary>
        internal static string TabCollection_BrowserTab_OnSettingCustomIcon_Custom_Icon {
            get {
                return ResourceManager.GetString("TabCollection_BrowserTab_OnSettingCustomIcon_Custom_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string TitanUploadPage_Title {
            get {
                return ResourceManager.GetString("TitanUploadPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the visibility of the password.
        /// </summary>
        internal static string TitanUploadPage_ToggleTokenVisibleHint {
            get {
                return ResourceManager.GetString("TitanUploadPage_ToggleTokenVisibleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle visible.
        /// </summary>
        internal static string TitanUploadPage_ToggleVisible {
            get {
                return ResourceManager.GetString("TitanUploadPage_ToggleVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        internal static string TitanUploadPage_TokenPlaceholder {
            get {
                return ResourceManager.GetString("TitanUploadPage_TokenPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string TitanUploadPage_UploadFile {
            get {
                return ResourceManager.GetString("TitanUploadPage_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Text.
        /// </summary>
        internal static string TitanUploadPage_UploadText {
            get {
                return ResourceManager.GetString("TitanUploadPage_UploadText", resourceCulture);
            }
        }
    }
}
