name: Build

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
          preferLatestVersion: true

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.403
          include-prerelease: false

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          distribution: microsoft
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore RosyCrow.csproj

      - name: Build
        run: dotnet build RosyCrow.csproj -c Release -f net7.0-android33.0 --no-restore -p:ApplicationDisplayVersion=${{ steps.gitversion.outputs.semVer }}
        env:
          ROSYCROW_SIGNING_KEY_PASSWORD: ${{ secrets.ROSYCROW_SIGNING_KEY_PASSWORD }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-${{ github.run_number }}-${{ steps.gitversion.outputs.semVer }}
          path: |
            bin\Release\net7.0-android33.0\app.rosy_crow-Signed.aab
            bin\Release\net7.0-android33.0\app.rosy_crow-Signed.apk
            bin\Release\net7.0-android33.0\mapping.txt
