name: Deploy a Beta Release
on:
  workflow_run:
    workflows: [ Build ]
    types:
      - completed
    branches: [ beta ]
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Beta (Google Play)
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        branch: beta
        allow_forks: false
    - name: Copy Files
      run: |
        cp ./**/*.apk .
        cp ./**/*.aab .
        cp ./**/version .
    - name: Read Version
      id: read_version
      run: echo "version=$(cat version)" >> "$GITHUB_OUTPUT"
    - name: Upload
      uses: r0adkll/upload-google-play@v1.0.19
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICES_ACCOUNT_JSON }}
        packageName: app.rosy_crow
        releaseFiles: app.rosy_crow-Signed.aab
        releaseName: ${{ steps.read_version.outputs.version }}
        track: beta
        status: completed
    - name: Create Tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: false
        CUSTOM_TAG: ${{ steps.read_version.outputs.version }}
