name: Draft a Beta Release
on:
  push:
    branches: [ beta ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ beta ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Beta (Google Play)
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
        preferLatestVersion: true
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
    - name: Download Bundle
      uses: actions/download-artifact@v3.0.2
      with:
        name: bundle-${{ steps.gitversion.outputs.semVer}}
    - name: Draft a Beta Release
      uses: r0adkll/upload-google-play@v1.0.19
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICES_ACCOUNT_JSON }}
        packageName: app.rosy_crow
        releaseFile: app.rosy_crow-Signed.aab
        releaseName: ${{ steps.gitversion.outputs.semVer }}
        status: draft
        track: beta
        mappingFile: mappings.txt
    - name: Create a Tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: v${{ steps.gitversion.outputs.semVer }}

        
