name: Deploy a Beta Release
on:
  workflow_run:
    workflows: [ Build ]
    types:
      - completed
    branches: [ beta ]
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to deploy
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Beta (Google Play)
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Install GitVersion
      if: ${{ github.event.inputs.version == '' }}
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
        preferLatestVersion: true
    - name: Determine Version
      if: ${{ github.event.inputs.version == '' }}
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
    - name: Set Version


